version: '3.7'

services:
  redis:
    image: redis
    ports:
     - 6379:6379
    command: ['redis-server', '--appendonly', 'yes'] # Overwrite the CMD
    volumes: # Declare the volume
      - redis_data:/data
  mongo:
    image: mongo
    ports:
     - 3456:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db
  server:
    image: todo-backend-dev
    build:
      context: . # The context will pick this directory as the "build context"
      dockerfile: dev.Dockerfile # This will simply tell which dockerfile to read
    volumes:
      - ./:/usr/src/app
    ports:
      - 3001:3001
    environment: 
      - PORT=3001
      - REDIS_URL=//redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database

volumes:
  mongo_data:
  redis_data: